### ISSUE TITLE
I can't get an access token

### ISSUE THREAD

**Issue by handplant** [ssplugin/ss-twitter-feed#18]
After clicking the button " Connect to twitter and get access token" in my local environment, I get the following error:

```
HTTP 404 – Not Found – yii\web\NotFoundHttpException
Caused by: Invalid Route – yii\base\InvalidRouteException
Unable to resolve the request: ss-twitter-feed/oauth/callback&oauth_token=XXXXXXXXX&oauth_verifier=XXXXXXXXX
```

PHP version: 7.4.5
Craft CMS: Craft Pro 3.5.4
SS Twitter Feed: 1.0.6

**Comment by ssplugin** [comment]
@handplant 

When error occurs when you click on the button "Connect to twitter for..." OR After you have entered twitter email, password and click on "Authorize app" Button???

Invalid route exception occurred means when twitter redirect to craft site after authenticated, It could not find proper redirect URL. 

Can you give some basic information about your local setup:
- Which platform you have used right now? like xampp, WAMP, LAMP.
- Please give your URL for example.
- Have you changed CpURl?

**Comment by b3nhartl3y** [comment]
Hey, I'm getting the same issue. 

It returns to `/actions/ss-twitter-feed/oauth/callback&oauth_token=EVY1XwAAAAAA9e5BAAABdC9ofRo&oauth_verifier=D1gSMXjyVemNPli8CJNMjvJb9TAYCkgE`

and gives 
`HTTP 404 – Not Found – yii\web\NotFoundHttpException
Page not found.
↵
Caused by: Invalid Route – yii\base\InvalidRouteException
Unable to resolve the request: ss-twitter-feed/oauth/callback&oauth_token=EVY1XwAAAAAA9e5BAAABdC9ofRo&oauth_verifier=D1gSMXjyVemNPli8CJNMjvJb9TAYCkgE
in /Users/benhartley/Sites/pensionawarenessday.com/vendor/yiisoft/yii2/base/Controller.php at line 151`

and on twitter it gives:
`Whoa there!
The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake.`

I'm using Valet.

--------------------------------

I've created a developer twitter account and set the app up manually and added the Access Token and Secret to the CMS, but now I'm getting:

`32Could not authenticate you.`

**Comment by ssplugin** [comment]
@b3nhartl3y 

Hey,
Please confirm, Have you faced "`Template not found`: `admin/settings/plugins/ss-twitter-feed`" Error occurred???
If above error occurred means you have changed `cpTrigger` setting in `general.php` file. We will fix this issue if you have faced.


For `32Could not authenticate you.` error means twitter can not able to authenticate you due to some reason.
I would suggest to you for this issue please use different twitter account and confirm it worked or not.

Let us know your answer about error that i have mention above.

Thanks

**Comment by watershed** [comment]
Just had a quick play with this plugin (which looks good) and dropping by to say I _have_ just encountered "`Template not found: admin/settings/plugins/ss-twitter-feed`". 

By changing `admin` to my `cpTrigger` I got back the authentication I needed.

But it would be good to fix this.

**Comment by fbnntt** [comment]
I'm currently getting this issue, but happening slightly differently...

I'm needing to manually change the URL from `http://` to `https://` (as it errors) then when I'm clicking the "Authorize app" button it's erroring to:
`https://site-url-here.test/actions/ss-twitter-feed/oauth/callback&oauth_token=_82cJwAAAAAA9e5BAAABd7YuxR0&oauth_verifier=4jQiNoE2Z8pE3XoPuZoMxJHjjgsyryil`

_Page not found.
Caused by: Invalid Route – yii\base\InvalidRouteException
Unable to resolve the request: ss-twitter-feed/oauth/callback&oauth_token=JAZ8rwAAAAAA9e5BAAABd7Y0qSQ&oauth_verifier=KJ5Ya8ePSDjEnKQ0zQFQo1OHl59Xmy2n_

Using Valet with `.test`
PHP `7.3.26`
Craft `3.5.19.1`
SS Twitter Feed `1.0.6`

For `cpTrigger` I've tried `admin` + changing to something else and still not working.

**Comment by ssplugin** [comment]
@watershed @fbnntt 
We have updated our plugin and fixed `cpTrigger` dynamic URL generation. Also, change `http://` to `https://`
Thanks.

**Comment by knynkwl** [comment]
I am also getting the same issue using valet. The local site is secured and using https (https://my-site.test/)

**Comment by knynkwl** [comment]
@ssplugin any ideas? I am using version **1.0.8**

**Craft CMS:** 3.7.3.1
**PHP:** 7.4.21

Happens after clicking on "Authorize app" Button in twitter. It says I am already logged in.

<img width="738" alt="Screen Shot 2021-07-25 at 8 22 10 AM" src="https://user-images.githubusercontent.com/4225771/126898815-a0151919-d75c-4f6a-b0c1-809ff8663c36.png">

Url it redirect to:
```
https://sitename.test/admin/actions/ss-twitter-feed/oauth/callback&oauth_token=QfRFCgAAAAAA9e5BAAABet2gyIc&oauth_verifier=4Bts2hBpeH8fZqyB659HmonqMTy2DaFl
```

```
HTTP 404 – Not Found – yii\web\NotFoundHttpException
Page not found.

Caused by: Invalid Route – yii\base\InvalidRouteException
Unable to resolve the request: ss-twitter-feed/oauth/callback&oauth_token=u1ZVEAAAAAAA9e5BAAABet2SP4E&oauth_verifier=dbk8vaMJHJjlfFJm8BHxoggoWjTR8cmB
in /Users/********/Sites/********/vendor/yiisoft/yii2/base/Controller.php at line 152
```

**Comment by ssplugin** [comment]
@knynkwl 
We have investigated this issue with the "Valet" installation.  But not found any issue.
Please share all the valet configuration and server information so we will easily track bugs.

**Comment by b3nhartl3y** [comment]
I'm getting the same issue as @knynkwl 

System screenshot:

![Screenshot 2021-07-29 at 17 00 03](https://user-images.githubusercontent.com/486062/127525581-6a7ee458-c093-4f65-9e6d-d14952fe9fb5.jpg)

**Comment by ssplugin** [comment]
@b3nhartl3y, @knynkwl 

Thanks for sharing details with us. 
Can you connect via email. Please send your system information like valet configuration and mac details.
Here is our contact email address: [ssplugins.seeders@gmail.com]
