### ISSUE TITLE
Cannot connect to Twitter account

### ISSUE THREAD

**Issue by koobadev** [ssplugin/ss-twitter-feed#28]
I'm not seeing any button to make the Twitter connection in the plugin settings, instead its returning the following message
Connect to a Twitter account click on button

**Something Wrong.**

SS Twitter Feed v1.0.6
Craft v3.5.16

Thanks!

**Comment by koobadev** [comment]
Hi I'm still seeing this issue of you could please review
Thanks!

**Comment by ssplugin** [comment]
@koobadev 

Actually, an error occurred because your server refused the post request and Twitter API needs a POST request.
So the solution is you need to replace post request with GET to the below line in the followig file:
`\vendor\ssplugin\ss-twitter-feed\src\services\SsTwitterFeedService.php`
**Line No.: 68** `$baseString = $this->buildBaseString($baseURI, $oauth, 'GET');`

**Line No.: 134**  `CURLOPT_POST => false, `
